flatcar-postinst, src/update_engine/omaha_response_handler_action.cc
For systems that updated from CoreOS CL the
correct path is /boot/coreos/vmlinux-* because
that is what GRUB uses.
Prefer /boot/coreos even if /boot/flatcar exists
to prevent the system from having the boot process
broken.
Note: Create a PR for coreos-overlay after merging (and also pick that for Alpha and Edge when merged).
=> Prefer /boot/coreos over /boot/flatcar

src/update_engine/omaha_request_action.cc, src/update_engine/omaha_request_action_unittest.cc
As detected in
https://github.com/kinvolk/nebraska/pull/152
the URL construction fails if the base URL does
not end with a slash.
Add a slash if it is missing when concatenating
the URL paths.
Fixes https://github.com/flatcar-linux/update_engine/issues/3
=> Concatenate URL paths with a slash if missing

flatcar-postinst, src/update_engine/omaha_response_handler_action.cc
In case a user or old software created the first_boot flag file under
/boot/coreos instead of /boot/flatcar, the update breaks because /boot/coreos
exists and is prefered ofer /boot/flatcar when the kernel is written.
Make updating more robust by checking if the kernel binaries exist which as least
allows the user to create /boot/coreos/first_boot without breaking the system.
See https://github.com/flatcar-linux/scripts/pull/68
Download the qemu image for arm64 from the linked PR above (because the amd64 did reuse the binary package):
```
$ wget https://storage.googleapis.com/flatcar-jenkins/developer/boards/arm64-usr/2345.3.1+dev-flatcar-master-449/flatcar_production_qemu_uefi_image.img.bz2
$ lbunzip2 flatcar_production_qemu_uefi_image.img.bz2
$ wget …
```
=> Prefer /boot/coreos only if /boot/coreos/vmlinux-* exists

src/update_engine/action_processor.h, src/update_engine/omaha_request_action.cc, src/update_engine/payload_state.cc, src/update_engine/utils.cc
When the system failed to boot into an update, a rollback to the
previous partition took place. However, an update success was reported
via Omaha.
Add a new error code that is reported for rollbacks. The detection is
done by comparing the currently running version number with the
previous version number that is already stored for reportting also
serves as a way to detect if a reboot is needed.
Build an image with this patch. Then run the following after booting it as VM:
```
sudo -s
echo "GROUP=stable" > /etc/flatcar/update.conf
curl -L -o /tmp/key https://raw.githubusercontent.com/flatcar-linux/coreos-overlay/flatcar-master/coreos-base/coreos-au-key/files/official-v2.pub.pem
sudo mount --bind /tmp/key /usr/share/update_engine/update-payload-key.pub.pem
cp /usr/share/flatcar/release …
```
=> Report rollbacks as Omaha error codes

src/update_engine/libcurl_http_fetcher.cc, src/update_engine/libcurl_http_fetcher.h, src/update_engine/omaha_request_params.cc, src/update_engine/omaha_request_params.h, src/update_engine/update_attempter.cc
This add user and password variables to the update config file to set
up HTTP Auth credentials for downloading the update payload.
Run a local Nebraska and edit the package of the stable channel to have the base URL https://postman-echo.com/ and the file name `basic-auth`.
Set the version of your image built with this PR after booting in QEMU:
```
cp /usr/share/coreos/release /tmp
sudo mount --bind /tmp/release /usr/share/coreos/release
sudo vi /tmp/release # overwrite version to be 1.1.1
```
Configure update-engine in /etc/flatcar/update.conf and restart the service:
```
SERVER=http://YOURNEBRASKA:PORT/v1/update
GROUP=stable
DOWNLOAD_USER=postman
DOWNLOAD_PASSWORD=password
```
Force an update with `update_engine_client -update` and observe the logs with `journalctl -u update-engine -e` …
=> Support HTTP Auth credentials for downloads

src/update_engine/omaha_request_action.cc, src/update_engine/omaha_request_params.cc, src/update_engine/omaha_request_params.h, systemd/update_engine_stub
The machine ID is the unique identifier of a client but it does not
carry much information about the machine and is hard to remember or
compare for humans. Nebraska supports an optional machinealias Omaha
field to display besides the machine ID.
Allow to set a MACHINE_ALIAS variable in the update.conf file to
specify the machine_alias field and fall back to the empty string
otherwise which will be ignored by Nebraska. As with the other
variables in /etc/flatcar/update.conf the MACHINE_ALIAS variable can be
changed while update-engine runs and it will pick up the change, which
is useful for scripts that set the machine alias like this:
```
sudo sed -i "/MACHINE_ALIAS=.*/d" /etc/flatcar/update.conf
echo "MACHINE_ALIAS=$(hostname)" | sudo tee -a /etc/flatcar/update.conf
```
Build an image …
=> Support optional machine alias besides the machine ID

src/update_engine/update_attempter.cc
omaha request params were not loaded after a restart if the status
of the `update-engine` is set to UPDATE_STATUS_UPDATED_NEED_REBOOT.
It leads to ping Omaha server with missing values in the payload and
an empty update server url.
To not introduce side effect, we duplicated the init code to the "if"
section
Signed-off-by: Mathieu Tortuyaux <mathieu@kinvolk.io>
Booted an image and assert that `update-engine` works as expected with "idle" status and "need reboot" status
closes https://github.com/kinvolk/Flatcar/issues/388
=> engine/update_attempter: init omaha request params

src/update_engine/update_engine_client.cc
idle status was not correctly handled by the update_engine.
When a user wants to check for an update with `update_engine_client -update`
the command will fail with "Update failed" which can be misleading.
Actually, the update does not failed it is just cancelled because there
is no newer version.
Signed-off-by: Mathieu Tortuyaux <mathieu@kinvolk.io>
build a Flatcar image using this commit in `coreos-base/update-engine` ebuild.
```
$ update_engine_client -update
I0702 14:33:22.542590   963 update_engine_client.cc:251] Initiating update check and install.
I0702 14:33:22.555794   963 update_engine_client.cc:256] Waiting for update to complete.
LAST_CHECKED_TIME=0
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_IDLE
NEW_VERSION=0.0.0
NEW_SIZE=0
I0702 14:33:28.111543   963 …
```
=> src/update_engine_client: handle -update with idle

.github/workflows/c-cpp.yml, src/update_engine/extent_mapper_unittest.cc, src/update_engine/omaha_request_action_unittest.cc, src/update_engine/payload_processor_unittest.cc
* tweaked the workflow yaml file to get the test binaries working
* fixed the immediate bug that was causing a segfault on startup
TODO:
See also kinvolk/Flatcar#282
=> Make unittest workflow work

.github/workflows/c-cpp.yml, src/update_engine/postinstall_runner_action.cc, src/update_engine/utils.cc
- postinstall: support btrfs as /usr filesystem
When btrfs is used to fit more content into the partition, mounting
fails because ext2/3 was hardcoded.
Also try to mount as btrfs if mounting as ext2/3 fails. The
norecovery options makes sure that the filesystem isn't touched even if
the it is corrupted.
- utils: support btrfs
With btrfs it's not possible in general to find a single underlying
block device because there could be many, but still it is possible for
our case since we have a single partition. However, rootdev failed to
find it because it uses the device minor and major pair from a "stat"
syscall on the mount point. This doesn't work with btrfs because it
gives a logical pair instead of one belonging to a block device.
Instead of using the minor and major pair, find the …
=> Support btrfs as /usr filesystem

flatcar-postinst
Changing cgroup setting on a provisioned system is guaranteed to cause trouble with kuberntes clusters. In order to not disturb operations during a routing update, a postinstall hook is added that modifies the OEM grub.cfg to keep the system on cgroupv1. This will allow us to migrate the alpha channel to cgroupv2.
Part of kinvolk/coreos-overlay#931
Boot alpha 2942.0.0.
Use https://github.com/kinvolk/Flatcar/issues/70#issuecomment-880441082 to update to a development snapshot containing this change.
=> add postinstall hook to stay on cgroupv1

flatcar-postinst
While locksmithd and FLUO interact with update-engine through DBus,
kured looks for Ubuntu's /run/reboot-required flag file.
Support kured by creating the flag file in the update post-install
action.
Apply an update with `flatcar-update` and see that kured will reboot the machine.
Booted the built image and updated to it:
```
sudo systemctl mask --now locksmithd
wget https://bucket.release.flatcar-linux.net/flatcar-jenkins/developer/developer/boards/amd64-usr/2021.12.06+dev-flatcar-master-4330/flatcar_test_update.gz
sudo flatcar-update -V 1.2.3 -P flatcar_test_update.gz -D
ls /var/run/reboot-required # check that the flag file got created
```
↑ will do in coreos-overlay
=> flatcar-postinst: create reboot-required flag file for kured

flatcar-postinst
The heredoc treated `=0` like $(=0), replacing this part of the
template with an empty string and logging "=0: commad not found".
Replace backticks by simple quotes which are not treated specially in
the template.
Update commit ID in overlay and backport to stable
Manual execution of the cat command.
↑ TODO in coreos-overlay
=> flatcar-postinst: fix template error command not found

src/update_engine/libcurl_http_fetcher.cc
This protobuf definition being used is no longer is provided with
libprotobuf-dev 3.12.4-1
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>
=> update_engine: remove undefined reference

flatcar-postinst
Starting from glibc 2.34, `flatcar-postinst` started to fail like:
```
update_engine: Failed to locate ld.so in /tmp/au_postint_mount.6RMfwL
```
While glibc 2.33 has `/lib64/ld-2.33.so`, glibc 2.34 does not have that, but only `/lib64/ld-linux-x86-64.so.2`. So we should also check `ld-linux-*` as well.
CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/490/cldsv/
- Changelog entries added in the respective `changelog/` directory (user-facing change, bug fix, security fix, update) (not needed)
=> flatcar-postinst: check also /lib64/ld-linux-*.so.2 for glibc 2.34

.github/workflows/c-cpp.yml
This avoids a warning about using deprecated features.
=> workflow: Update actions/checkout to v3

flatcar-postinst
The newer Omaha 3.1 hash_sha256 attribute is now supported by Nebraska and should be used for OEM payloads. Up to now we only checked the regular "hash" attribute for download integrity. It's not really security critical because the payload has its own signature but it's good to migrate all hashsum usage away from SHA1.
Find the hash and hash_sha256 attributes and require at least one to be set for the OEM packages. Check the found hash attributes.
[Jenkins](http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/2598/cldsv/): `cl.update.oem` passed.
I've also checked that the `flatcar-update` invocation uses the XML dump.
=> flatcar-postinst: In addition to SHA1, also check SHA256 hash for OEMs

flatcar-postinst
When the old OEM contents and a yet inactive systemd-sysext image are on the OEM partition (or if no two sysexts fit on it), it can fail to write the second systemd-sysext image on the OEM partition and the rootfs is used instead. However, "mv" doesn't clean up the incomplete target file which filled the disk, this results in the migration flag file creation to fail, which fails the update action.
Clean up the incomplete move target that filled the disk.
Backport to Alpha/Beta because this fixes the problem of not being able to update from ≤ 3619.0.0
in https://github.com/flatcar/scripts/pull/1272
=> flatcar-postinst: Clean up incomplete move target

flatcar-postinst
This change removes torcx sanity checks in the `flatcar-postinst` post-install script. This allows future major releases to of docker and containerd sysexts instead of torcx without the post-install script breaking.
An earlier version of this PR wrapped torcx sanity checks in a version check of the new OS version to be installed. If MAJOR > 3760 then torcx sanity checks are not run; this was removed during review.
If we need to issue updated update_engine releases to older major versions too, e.g. for bug fixes / security fixes, we'll create a branch with a back-port of the respective change.
=> flatcar-postinst: Remove torcx sanity checks

decode_payload
Either the printf escaping gives wrong binary data or the random dummy key signature is really broken for the oem-ami.gz 3745.1.0 amd64 payload.
The error reported is:
RSA operation error
007E9295D47F0000:error:02000084:rsa routines:rsa_ossl_public_decrypt:data too large for modulus:crypto/rsa/rsa_ossl.c:661: 007E9295D47F0000:error:1C880004:Provider routines:rsa_verify_recover:RSA lib:providers/implementations/signature/rsa_sig.c:748:
Backport to Beta
```
wget -O /var/tmp/oem-ami.gz https://update.release.flatcar-linux.net/amd64-usr/3745.1.0/oem-ami.gz
PROTOPATH=src/update_engine/ ./decode_payload ~/flatcar/scripts/sdk_container/src/third_party/coreos-overlay/coreos-base/coreos-au-key/files/official-v2.pub.pem /var/tmp/oem-ami.gz /var/tmp/out
```
=> decode_payload: Skip over signature entries that cause errors

flatcar-postinst
In Beta 3760.1.0 the /etc/extensions/ folder gets created by "mkdir -p" because it does not exist in the lowerdir /usr/share/flatcar/etc/. This causes the opaque marker to be set by overlayfs. The update to Alpha thus does not merge the new /usr/share/flatcar/etc/extensions/ folder with its docker/containerd sysext symlinks. We should have had /etc/extensions/ in the lowerdir in Beta but didn't.
Ensure that the created folders are mergable by removing the overlayfs marker. This is needed for existing installations and folders we expect to exist in the lowerdir but were missing so far.
Backport to Alpha and Beta
Update from Beta to this here with `sudo flatcar-update -D -V 1.2.3 -E flatcar_test_update-oem-qemu.gz -P flatcar_test_update.gz` and after the reboot the extension folder has all …
=> flatcar-postinst: Ensure /etc/extensions is mergable

flatcar-postinst, src/update_engine/omaha_request_action.cc, src/update_engine/omaha_request_action.h, src/update_engine/omaha_request_action_unittest.cc, src/update_engine/update_attempter.cc, src/update_engine/update_attempter_unittest.cc
The full Omaha XML response is stored to a file for the postinst action, but we only want the response for the initial update check passed this way and not overwrite the file with responses for state reports. Only store the Omaha XML response for the update check and not all of the interaction with the Omaha server.
Fixes https://github.com/flatcar/Flatcar/issues/1281
Backport to Beta
Fixes https://github.com/flatcar/Flatcar/issues/1281
From the new image to the new image works with
```
flatcar-update -V 1.2.3 -E flatcar_test_update-oem-qemu.gz -P flatcar_test_update.gz
```
and does not use the fallback path.
The previous-version file is modified earlier than the full-response file until the update is complete when it gets modified again:
```
localhost /var/lib/update_engine/prefs # stat …
```
=> Only store Omaha XML response for update check

flatcar-postinst
The ue-rs download_sysext binary can now do what was done in bash with curl plus decode_payload before.
Switch to make use of the binary.
Needs https://github.com/flatcar/ue-rs/pull/47
Partly addresses https://github.com/flatcar/Flatcar/issues/1028
see scripts PR https://github.com/flatcar/scripts/pull/1541
=> flatcar-postinst: Make use of ue-rs download_sysext binary

flatcar-postinst
Nebraska servers with self-hosted synced packages use Omaha entries with names like extrafile-amd64-3815.0.0-oem-ami.gz which can't be predicted. The ue-rs matching option is not enough and we also need to control the target filename because otherwise it would be
extrafile-amd64-3815.0.0-oem-ami.raw which we can't know either and using shell globs is not the nicest solution.
Make use of two new ue-rs parameters to control the target filename and make sure that we only use one match result.
Depends on https://github.com/flatcar/ue-rs/pull/49
see scripts branch
=> flatcar-postinst: Control target filename of extracted OEM payload

src/update_engine/subprocess.cc
The proxy env vars for curl can be set up for the update-engine service but so far weren't forwarded to the postinstall script. Now that we download from it, we need to forward them.
Forward the env vars for curl and ue-rs download_sysext (Flatcar Stable currently uses curl, Alpha uses ue-rs).
Backport to Stable and LTS.
Checked that these env vars pop up when set up. First I tested
```
[Service]
Environment="LD_LIBRARY_PATH=/usr/lib64"
```
with `sudo flatcar-update …` and it made one more env var entry (`2 vars`). The same should happen for the proxy vars.
```
sudo strace -f -e trace=execve -p $(pgrep update_engine) 2>&1 | grep postinst
[pid 163396] execve("/tmp/au_postint_mount.DzIv8e/postinst", ["/tmp/au_postint_mount.DzIv8e/pos"..., "/dev/vda4", "KERNEL=/boot/flatcar/vmlinuz-b"], …
```
=> subprocess: Forward proxy env for postinstall script

flatcar-postinst
The XML passing and the passing of proxy env vars is required for updating old airgapped clients because we need to support custom non-public payload URLs and/or go through a proxy. However, these changes are part of update-engine itself and thus are not present in old clients. This blocks updating to the latest Stable.
Add two workarounds to read out proxy env vars from the service unit and to read out the XML response from the journal logs.
Backport to Stable
[Jenkins](http://jenkins.infra.kinvolk.io:8080/job/container/job/packages_all_arches/3417/cldsv/)
Tested running the commands manually.
Tested the "inverse" with an invalid proxy env var added while the update-engine service is running to see that the variable gets read in from the postinst action and it is thus by not being able …
=> flatcar-postinst: Support updating old airgapped clients

flatcar-postinst
This is a backport of the equivalent of https://github.com/flatcar/scripts/pull/1580 to 3815, without switching to ue-rs.
Tested on the full-response from the airgapped environment (in commit message):
```bash
$ cat flatcar-postinst
set -euo pipefail
set -x
umask 0022
OEMID=vmware
sysext_download() {
....
}
sysext_download "oem-${OEMID}.gz" "./var/lib/update_engine/oem-${OEMID}.raw" test.xml
```
Output:
```bash
$ bash -x flatcar-postinst
+ set -euo pipefail
+ set -x
+ umask 0022
+ OEMID=vmware
+ sysext_download oem-vmware.gz ./var/lib/update_engine/oem-vmware.raw test2.xml
+ local name=oem-vmware.gz
+ local target=./var/lib/update_engine/oem-vmware.raw
+ local from=test2.xml
+ local base=
+ local entries=
+ local hash=
+ local size=
+ local url=
+ local ret
+ SUCCESS=false
+ set +e
+ set …
```
=> flatcar-postinst: Handle airgapped self-hosted nebraska instances

src/update_engine/postinstall_runner_action.cc
It looks like 'norecovery' is deprecated and has been removed in the v6.8-rc1 kernel. Replace it with 'rescue=nologreplay', which is a replacement implemented since v5.9. The standalone 'nologreplay' option is also deprecated.
See: https://lore.kernel.org/linux-btrfs/91c34f25266be07585b75fde0b580b9118f8786e.1700673401.git.josef@toxicpanda.com/
=> Mount btrfs fs with rescue= option

.github/workflows/c-cpp.yml
Rename the default branch from `flatcar-master` to `main`, following the general Flatcar repo settings guideline.
Note: we should not touch download URLs of seismograph yet, which should be updated afterwards.
=> .github: rename default branch from flatcar-master to main

.github/workflows/c-cpp.yml
Update the default branch name of seismograph, from `flatcar-master` to `main`, as part of https://github.com/flatcar/Flatcar/issues/1714.
See also https://github.com/flatcar/seismograph/pull/10.
Also rename `kinvolk` to `flatcar`.
=> .github: fix the default branch name of seismograph

src/update_engine/test_http_server.cc
Potential fix for [https://github.com/flatcar/update_engine/security/code-scanning/2](https://github.com/flatcar/update_engine/security/code-scanning/2)
To fix the issue, we need to ensure that the lifetime of the `std::string` object returned by `Get(index)` is extended so that the pointer returned by `c_str()` remains valid. The best way to achieve this is to store the `std::string` object in a local variable within the `GetCStr` method and return the pointer to its character array. This ensures that the `std::string` object outlives the call to `c_str()`.
Changes will be made to the `GetCStr` method in the `UrlTerms` class. Specifically:
1. Store the result of `Get(index)` in a local variable.
2. Call `c_str()` on the local variable and return the pointer.
No additional imports or …
=> Potential fix for code scanning alert no. 2: Use of string after lifetime ends
